/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as ViewIndexRouteImport } from './app/view/index'
import { Route as VideoIndexRouteImport } from './app/video/index'
import { Route as VideoWindowIndexRouteImport } from './app/video-window/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewIndexRoute = ViewIndexRouteImport.update({
  id: '/view/',
  path: '/view/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoIndexRoute = VideoIndexRouteImport.update({
  id: '/video/',
  path: '/video/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoWindowIndexRoute = VideoWindowIndexRouteImport.update({
  id: '/video-window/',
  path: '/video-window/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/video-window': typeof VideoWindowIndexRoute
  '/video': typeof VideoIndexRoute
  '/view': typeof ViewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/video-window': typeof VideoWindowIndexRoute
  '/video': typeof VideoIndexRoute
  '/view': typeof ViewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/video-window/': typeof VideoWindowIndexRoute
  '/video/': typeof VideoIndexRoute
  '/view/': typeof ViewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/video-window' | '/video' | '/view'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/video-window' | '/video' | '/view'
  id: '__root__' | '/' | '/video-window/' | '/video/' | '/view/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VideoWindowIndexRoute: typeof VideoWindowIndexRoute
  VideoIndexRoute: typeof VideoIndexRoute
  ViewIndexRoute: typeof ViewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/': {
      id: '/view/'
      path: '/view'
      fullPath: '/view'
      preLoaderRoute: typeof ViewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/': {
      id: '/video/'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-window/': {
      id: '/video-window/'
      path: '/video-window'
      fullPath: '/video-window'
      preLoaderRoute: typeof VideoWindowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VideoWindowIndexRoute: VideoWindowIndexRoute,
  VideoIndexRoute: VideoIndexRoute,
  ViewIndexRoute: ViewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
