/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as MediaWindowRouteImport } from './app/media-window'
import { Route as IndexRouteImport } from './app/index'

const MediaWindowRoute = MediaWindowRouteImport.update({
  id: '/media-window',
  path: '/media-window',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/media-window': typeof MediaWindowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/media-window': typeof MediaWindowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/media-window': typeof MediaWindowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/media-window'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/media-window'
  id: '__root__' | '/' | '/media-window'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MediaWindowRoute: typeof MediaWindowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/media-window': {
      id: '/media-window'
      path: '/media-window'
      fullPath: '/media-window'
      preLoaderRoute: typeof MediaWindowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MediaWindowRoute: MediaWindowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
